export const mapColorToLine: { [key: string]: string } = {
  '1': 'red',
  '2': 'red',
  '3': 'red',
  '4': 'green',
  '5': 'green',
  '6': 'green',
  '7': 'purple',
  A: 'blue',
  C: 'blue',
  E: 'blue',
  B: 'orange',
  D: 'orange',
  F: 'orange',
  M: 'orange',
  G: 'lime',
  J: 'brown',
  Z: 'brown',
  L: 'grey',
  N: 'yellow',
  Q: 'yellow',
  R: 'yellow',
};
