export const GET_STOPS_FOR_SUBWAY_LINE = 'GET_STOPS_FOR_SUBWAY_LINE';
export const GET_CURRENT_POSITIONS_FOR_SUBWAY_LINE =
  'GET_CURRENT_POSITIONS_FOR_SUBWAY_LINE';
export const GET_TRIPS_FOR_SUBWAY_LINE = 'GET_TRIPS_FOR_SUBWAY_LINE';
